---
apiVersion: v1
kind: Pod
metadata:
    name: myfirstpodwithsvc
    labels:
        app: myapp1
spec:
    containers:
    name: myfirstpodwithsvc1
    image: kv007/02govindait02
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: mysvcwithpod
spec:
    type: NodePort
    selector:
        app: myapp1
    ports:
    - port: 80
    targetPort: 8080
    nodePort: 30850
...